### ISSUE TITLE
✋ Looking for maintainer

### ISSUE THREAD

**Issue by simonwep** [Simonwep/java-express#13]
Last time I actively worked on it is almost a full year ago. I'm not longer working with java and I'm looking for someone new to maintain this project / addressing existing issues which I, considering my limited experience with Java, cannot fix / implement anymore (the last version I worked with was Java 8 which is quite ancient I guess).

Please write a comment below if you're interested.

**Comment by jjzazuet** [comment]
I think I can help. What does your backlog look like? Let me know in case you're interested. Thanks!

**Comment by simonwep** [comment]
Hey @jjzazuet  :)

I don't have road-map or something similar (but we could create one) so here's a list of things which I could think of:

1. Publishing it (again) on maven, as I published it the whole process was, at least to me, overly complicated and I just decided to stick to github releases. So either java-express could be published on a public package-manager or we could add a github action to build `.jar` files on every release and upload them as release artifact to every release.
2. As I wrote this Java8 was the latest version, maybe its source code could be updated to Java15? Also, I didn't know that Java has asynchronous support (Futures apparently are they called) so that might be a cool feature, see #11 
3. Whups, this questions from you #10 - sorry I barely looked at this repo anymore, as for my answer: I don't really know how that could be done. If there's a clean way to do this it might be a nice addition to the readme :D
4. The whole readme probably needs to be refactored, at least the written part to make it look less amateurish.
5. I don't know what was added to [expressjs](https://expressjs.com/) but maybe I'd be cool to add things like json support (could this be an optional api?)  and fill all the gaps between what features expressjs has and which java-express actually implements. Also there's an alpha for the [fifth version](https://expressjs.com/en/5x/api.html) of expressjs which probably also comes with a whole new set of features.

Since I'm not working with Java (anymore) I don't know anything about the quality of the overall project structure so that could probably also require some work.

**Comment by jjzazuet** [comment]
Hi @Simonwep , thanks for getting back.

Most of these points should be easy to cover. Point 1 would be the most important. That said:

1. I already own the `vacco.io` namespace and DNS records in both JCenter and Maven Central, and I already have code build infrastructure in place to publish release artifacts, so I can cover this process. For this, I can either fork your repository under my Github org [vaccovecrana](https://github.com/vaccovecrana), or you can transfer the repository directly to the organization as well (I will assign admin rights to you for that repository).
2. From what I've been surveying, right now most libraries stick to remain either Java 8 or Java 11 compatible (since both are long term support releases). If you want a larger user base to adopt the library, stick only to those versions.
3. It's alright, I will probably contribute this work myself :P.
4. Should still be manageable via PRs in the repository.
5. Same as 4.

For 4 and 5 (and the last comment), I can create milestones after I apply build optimizations to the build repository. Given from what I saw in the code, this library should be fairly easy to maintain ans support.

Let me know how you'd like to proceed. Cheers.

**Comment by simonwep** [comment]
That sounds great! Only one thing which is that I'd prefer to keep this repository here as many people use [jitpack](https://jitpack.io/) and I'd be confusing if it just disappear (also for personal reasons). I'd add you as a collaborator so you'll have full access over all repo-features if that's ok.

**Comment by jjzazuet** [comment]
@Simonwep sounds good to me. Let me know when collaborator access is available, and I'll send some PRs to improve the build and release process. Cheers!

**Comment by simonwep** [comment]
You should have got an [invitation link](https://github.com/Simonwep/java-express/invitations). I'm exited for the future of this project and I'm looking forward to your PR's! :)

**Comment by jjzazuet** [comment]
Received. Will begin setup this week.

Cheers.
